name: Bot Test Gemini

on:
  workflow_dispatch:   # 👈 Esto permite que lo ejecutes manualmente desde GitHub Actions

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script de prueba
        run: python bot_autorun_test.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
