name: Bot Predicciones Automático

on:
  schedule:
    # Cada hora a minuto 0 UTC → 7 a.m., 8 a.m., etc., hora Lima
    - cron: '0 * * * *'
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar bot optimizado
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_autorun_opt.py
